### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by gabynnette** [DDihanov/musiQ#11]
Hello friend, I've seen a few days ago that you need a logo for your app, I've created something that you're going to love I hope your approval. All this is totally free I like to collaborate with the Git community.

![musiq](https://user-images.githubusercontent.com/39386395/40200140-8ef4822c-59e9-11e8-9064-1ad607bed8e9.png)

**Comment by DDihanov** [comment]
Hey thanks for the issue and the interest!

Some things to mind:

if you can please spell "musiQ" like that and not "MusiQ".
And the requirements were:

First for the icon that will be on the phone desktop I need two icons both identical. 
I really like the music player icon you used on the logo, so if you can make that into the desktop icon(with the background part transparent, so only the logo with the headphones and the play button is there) it would be great! One icon must be 24x24 png and the other 96x96 png.

Next is a 24x24 black/white icon for the notification bar(this can be the same as the desktop icon, but it must be black and white)

Next is a 512 x 512 32-bit PNG with alpha(this is just like the main icon for the desktop - but only bigger - as it will be displayed in the google play store)

Next is a 1024 w x 500 h jpg or 24-bit PNG with no alpha for the store banner. This is the banner that will be displayed when the user clicks the app in the play store. I personally like the 3rd one for the store banner, but if you can add the text from the first image to it - it would be great! 

Also one thing:
since the application main theme is mint green(https://play.google.com/store/apps/details?id=com.dihanov.musiq), if you can think of another color that goes with that mint green for the main logo I would be really thankful!

Thanks for the help!

**Comment by gabynnette** [comment]
Hi, I think we should work based on that color and the one I'm placing here in the sample, it's a kind of very faint gray and it goes very well with that green mint base of the app...


![musiq](https://user-images.githubusercontent.com/39386395/40255760-4c38ee50-5ab6-11e8-89b9-309477b06228.png)

**Comment by DDihanov** [comment]
Oh yeah this is great! Looks super nice :)

**Comment by gabynnette** [comment]
In short, we are left with this color ?? Do you think you can close this problem, and prepare all the editable files to create an extraction request here in git and can be coupled to the project?

**Comment by DDihanov** [comment]
Oh yeah, so the color is great. So one last thing is if you can make the 24x24 and 96x96 headphone logos in green and in white(since I will add one of them in the splash screen when the app starts up :) ).

If you want you can make a pull request and make a new folder called "logos" or "application art" or something in the root of the project and put your stuff there. From there I can then edit them into the project. Other option is to just send them to me on the email. It's up to you.

Please note that in both cases I will update the project README to give you credit for the designs, so don't worry about that. I will close the issue when the logos are done, just so we have a place to discuss things.
